Minimal_Alk_pH_AirSea:

    domains:


        global:

            reactions:

                sum_C:

                    class: ReactionSum

                    parameters:

                        vars_to_add: ["ocean.DIC_total", "atm.CO2"]

                    variable_links:

                        sum: C_total

                add_Alk:
                    # from PALEOboxes reaction catalog:  constant input flux of Alk
                    class: ReactionFluxPerturb
                    parameters:
                        # linear interpolation for input flux - set to constant
                        perturb_times: [-1e30, 1e30]
                        # ocean volume = 3.6e14 * 3688.0 = 1.33e18 m^3
                        # DIC in ocean = 2 * 1.33e18 = 2.66e18 mol
                        # set Alk flux so Alk = DIC after 100 yr-1 = 2.66e18/100 = 2.66e16 mol yr-1
                        perturb_totals: [2.66e16, 2.66e16] 
                    variable_links:
                        F: ocean.TAlk_sms  # add flux to TAlk reservoir NB: works for single-box ocean only !!



 # --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------       

        ocean:

            reactions:

                oceantrasport:

                    class: ReactionOceanNoTransport

                    parameters:

                        area:  [3.6e14]               
                        depth: [3688.0]               



                reservoir_TA:

                    class: ReactionReservoirTotal
                   
                    variable_links:
                        R*: TAlk*
                    variable_attributes:
                        R:initial_value:  0.0                  
                        R:norm_value:     2.4e0                



                reservoir_DIC:
                    class: ReactionReservoirTotal
                   
                    variable_links:
                        R*: DIC*
                    variable_attributes:
                        R:initial_value:  2.0e0   
                        R:norm_value:     2.0e0   

                constant_B:
                    class: ReactionReservoirConst
                    variable_links:
                        R*: B
                    variable_attributes:
                        R_conc:initial_value: 0.427 # mol m-3 contemporary value

                solve_Alk_pH:

                    class: Reaction_Alk_pH
                    
                    parameters:                         

                        K_1:               1.4e-6                              
                        K_2:               1.2e-9                             
                        K_w:               6.0e-14                            
                        K_B:               2.5e-9                                

                    variable_links:
                        density: rho_ref   # OceanNoTransport provides density as rho_ref             


# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

        oceansurface:

            # air-sea exchange reactions

            reactions:
                # calculate air-sea exchange flux
                solve_AirSea_Exchange:

                    class: Reaction_Min_AirSeaExchange
                    
                    parameters:

                        K_0:                    3.4e1 # (mol m-3 atm-1) = 3.4e-2 (mol L-1 atm-1) * 1e3 (L m-3)
                        vpiston:                1138.8 # m yr-1
                    
                    variable_links:  

                        pXatm:    atm.pCO2atm
                        X_aq_conc: ocean.oceansurface.CO2_aq_conc         

                        area:       Asurf  # ocean surface area

                        X_airsea_exchange: fluxAtmtoOceansurface.flux_CO2


                # apply air-sea flux to ocean surface
                transfer_fluxAtmtoOceansurface:

                    class: ReactionFluxTransfer

                    parameters:

                        transfer_matrix:      Identity
                        input_fluxes:         fluxAtmtoOceansurface.flux_$fluxname$
                        output_fluxes:        ocean.oceansurface.$fluxname$_sms  

                    variable_links:                        

                        output_CO2:           ocean.oceansurface.DIC_sms 

# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

        oceanfloor:

# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

        atm:
            

            reactions:

                reservoir_CO2_atm:

                    class: ReactionReservoirAtm

                    parameters:

                        moles1atm:          1.77e20       


                    variable_links:

                        R*: CO2*
                        pRatm: pCO2atm
                        pRnorm: pCO2PAL

                    variable_attributes:

                        R:norm_value:       4.956e16     # 280e-6 ppm
                        R:initial_value:    4.956e16      

                transfer_AtmtoOceansurface:

                    class: ReactionFluxTransfer

                    parameters:
                    
                        transfer_matrix:      Distribute                                               
                        transfer_multiplier:  -1.0                                                     
                        input_fluxes:         fluxAtmtoOceansurface.flux_$fluxname$                
                        output_fluxes:        $fluxname$_sms                                           
                    
                    variable_links:           

                        output_CO2:           atm.CO2_sms 



                        

# --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

        fluxAtmtoOceansurface:    

            reactions:

                fluxtarget:

                    class: ReactionFluxTarget      

                    parameters:

                        flux_totals: true                            

                        fluxlist: ["CO2"]                        





